--- #YAML:1.0
name:                Date-Holidays-NZ
version:             1.02
abstract:            Determine New Zealand public holidays
license:             ~
author:              
    - Sam Vilain (samv@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Manip:                   0
    Set::Object:                   1.09
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
