# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Holidays-NZ
version:      1.01
version_from: NZ.pm
installdirs:  site
requires:
    Date::Manip:                   0
    Set::Object:                   1.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
